remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

![Gatinho fofinho](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.megacurioso.com.br%2Festilo-de-vida%2F117211-21-fotos-dos-gatos-mais-fofos-ja-vistos-para-alegrar-o-fim-de-ano.htm&psig=AOvVaw0qRrEsPVwMUUlgs8PRGgiU&ust=1668357432551000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCOiC6vKJqfsCFQAAAAAdAAAAABAE)
